plugins {
    id 'java-library'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'sparta.project.logistics.global'
version = '0.0.1-SNAPSHOT'

ext {
    set('springCloudVersion', "2024.0.0")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

configurations {
    jwtLib {
        canBeResolved = true
        canBeConsumed = true
    }
    securityLib {
        canBeResolved = true
        canBeConsumed = true
    }
    feignLib {
        canBeResolved = true
        canBeConsumed = true
    }
    implementation.extendsFrom(jwtLib, securityLib, feignLib)
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.12"
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

def querydslDir = "src/main/generated"

sourceSets {
    main.java.srcDirs += [querydslDir]
}

tasks.withType(JavaCompile).configureEach {
    options.getGeneratedSourceOutputDirectory().set(file(querydslDir))
    options.compilerArgs += "-parameters"
}

clean {
    delete file(querydslDir)
}

dependencies {

    implementation 'org.springframework.boot:spring-boot-starter-web'

    compileOnly 'org.springframework:spring-web'
    compileOnly 'org.springframework.boot:spring-boot-starter-data-jpa'

    api "com.querydsl:querydsl-jpa:5.0.0:jakarta"
    api "com.querydsl:querydsl-apt:5.0.0:jakarta"


    compileOnly "com.querydsl:querydsl-apt:5.0.0:jakarta"
    compileOnly "jakarta.persistence:jakarta.persistence-api"
    annotationProcessor "com.querydsl:querydsl-apt:5.0.0:jakarta"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"

    compileOnly 'org.springframework:spring-webmvc'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    jwtLib 'io.jsonwebtoken:jjwt-api:0.12.6'
    jwtLib 'io.jsonwebtoken:jjwt-impl:0.12.6'
    jwtLib 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    feignLib 'io.github.openfeign:feign-hc5:13.2.1'
    feignLib 'org.springframework.cloud:spring-cloud-starter-openfeign'
    feignLib 'org.springframework.cloud:spring-cloud-starter-loadbalancer'

    securityLib 'org.springframework.boot:spring-boot-starter-security'
    securityLib 'org.springframework.boot:spring-boot-starter-web'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

artifacts {
    jwtLib jar
    securityLib jar
    feignLib jar
}
tasks.withType(Test).configureEach {
    systemProperty "file.encoding", "UTF-8"
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
tasks.named('test') {
    useJUnitPlatform()

    def envFile = rootProject.file('.env')
    if (envFile.exists()) {
        envFile.eachLine { line ->
            if (line.trim() && !line.startsWith('#')) {
                def (key, value) = line.tokenize('=')
                environment key.trim(), value.trim()
            }
        }
    }
    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
        exceptionFormat = "full"
    }
}