server:
  port: ${ORDER_SERVICE_PORT:17003}

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:logistics}?currentSchema=${POSTGRES_ORDER_SCHEMA:order_service}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:winner}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        default_schema: ${POSTGRES_ORDER_SCHEMA:order_service}
    show-sql: ${JPA_SHOW_SQL:false}
    open-in-view: false
    defer-datasource-initialization: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:17001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90