spring:
  application:
    name: orderservice

  eureka:
    client:
      enabled: ${EUREKA_CLIENT_ENABLED:true}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${POSTGRES_ORDER_SCHEMA}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        default_schema: ${POSTGRES_ORDER_SCHEMA}
    show-sql: ${JPA_SHOW_SQL:false}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_ENABLED:true}
    fetch-registry: ${EUREKA_CLIENT_ENABLED:true}