spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:logistics}?currentSchema=${POSTGRES_ORDER_SCHEMA:order_service}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:winner}
    password: ${POSTGRES_PASSWORD:winner1234}
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        default_schema: ${POSTGRES_ORDER_SCHEMA:order_service}
    show-sql: ${JPA_SHOW_SQL:false}
    open-in-view: false
    defer-datasource-initialization: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:redis1234}

eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_ENABLED:false}
    fetch-registry: ${EUREKA_CLIENT_ENABLED:false}