-- schema 생성
CREATE SCHEMA IF NOT EXISTS user_db;
CREATE SCHEMA IF NOT EXISTS company_db;
CREATE SCHEMA IF NOT EXISTS hub_db;
CREATE SCHEMA IF NOT EXISTS product_db;
CREATE SCHEMA IF NOT EXISTS order_db;
CREATE SCHEMA IF NOT EXISTS delivery_db;
CREATE SCHEMA IF NOT EXISTS notification_db;